### ISSUE TITLE
8ch extension disfunctions

### ISSUE THREAD

**Issue by aelsch** [f77/Dashchan#11]
Functions of 8chan extension stopped working. Until some days ago it did still operate when user edited the domain to 8kun.top, but now New thread or New post options give error HTTP 403: Forbidden.

**Comment by f77** [comment]
I don't use this imageboard and I will not fix it. Fix it yourself, make a pull request and I'll release it into the app.

**Comment by cm-mc** [comment]
It's working; just open User boards, on the menu, and they're all there.
