### ISSUE TITLE
"show more" popup not working when clicked on android 10

### ISSUE THREAD

**Issue by piguet** [f77/Dashchan#12]
When I open a thread and there are new comments, a pop-up "show more" appears at the bottom, but if I click it it does nothing. Previously it was leading to the new comments

**Comment by nVoxel** [comment]
Подтверждаю. Кнопка "открыть тред" в тосте на Android 10 тоже некликабельна.
![Screenshot_20200301-222659](https://user-images.githubusercontent.com/37751284/75632398-aec91c80-5c0c-11ea-867b-866b58ba9a93.png)

**Comment by 0x0000beef** [comment]
Подтверждаю, после вчерашнего security update на OnePlus 5 перестало нажиматься.

Upd: 2.13 пофиксил проблему, спасибо.
